repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: fixit
        name: fixit
        entry: uv run --no-sync python -m fixit lint
        language: system
        types: [python]
        pass_filenames: true
      - id: pyright
        name: pyright
        entry: uv run --no-sync pyright
        language: system
        types: [python]
        pass_filenames: false
