# spec: specs/debug-toggle-command.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .helpers import Discord


def test_debug_toggle_responds_both_directions(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    first = discord.send_and_wait(
        master_channel, "/debug", sentinel=False, timeout=15.0
    )
    text_one = discord.bot_response_text(first).lower()
    assert "debug mode" in text_one, (
        f"First /debug reply missing 'debug mode'. Got: {text_one[:300]!r}"
    )

    second = discord.send_and_wait(
        master_channel, "/debug", sentinel=False, timeout=15.0
    )
    text_two = discord.bot_response_text(second).lower()
    assert "debug mode" in text_two, (
        f"Second /debug reply missing 'debug mode'. Got: {text_two[:300]!r}"
    )
