# spec: specs/status-command-reports.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .helpers import Discord


def test_status_command_returns_master_info(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    msgs = discord.send_and_wait(
        master_channel, "/status", sentinel=False, timeout=30.0
    )
    text = discord.bot_response_text(msgs)
    assert text.strip(), "/status reply was empty"
    lowered = text.lower()
    assert "axi-master" in lowered or "master" in lowered, (
        f"/status reply did not mention master. Got: {text[:300]!r}"
    )
