# spec: specs/readme-channel-has-content.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from .conftest import INSTANCE_DIR

if TYPE_CHECKING:
    from .helpers import Discord


def test_readme_channel_exists_and_has_content(discord: Discord) -> None:
    readme_file = INSTANCE_DIR / "readme_content.md"
    if not readme_file.exists() or not readme_file.read_text().strip():
        pytest.skip(f"{readme_file} not present — bot skips readme sync, nothing to assert")

    readme_ch = discord.find_channel("readme")
    assert readme_ch is not None, "No #readme channel found in the test guild"

    messages = discord.history(readme_ch, limit=5)
    assert messages, "#readme channel has no messages"

    text = "\n".join(m.get("content", "") for m in messages)
    assert len(text) > 20, (
        f"#readme content unexpectedly short ({len(text)} chars): {text[:100]!r}"
    )
