# spec: specs/duplicate-live-agent-name.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

from .axi_e2e import AxiDiscordEntrypoints
from .conftest import agent_cwd

if TYPE_CHECKING:
    from .helpers import Discord


DUPLICATE_PHRASES = ("already", "exists", "duplicate", "in use")


def test_spawning_duplicate_live_name_is_rejected(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    name = f"smoke-dupe-{int(time.time() * 1000)}"
    master = discord.channel(master_channel, name="axi-master")
    axi = AxiDiscordEntrypoints(master)
    try:
        axi.spawn_agent(
            name=name,
            cwd=agent_cwd(name),
            prompt="Say OK",
            command="prompt",
            timeout=180.0,
        )
        discord.wait_for_channel(name, timeout=60.0)

        second_attempt = master.send_and_wait(
            f'Spawn an agent named "{name}" with cwd "{agent_cwd(name)}" and prompt "Say OK again"',
            timeout=60.0,
        )
        text = discord.bot_response_text(second_attempt).lower()
        assert any(phrase in text for phrase in DUPLICATE_PHRASES), (
            "Master did not reject duplicate live agent name. "
            f"Expected one of {DUPLICATE_PHRASES!r} in reply, got: {text[:300]!r}"
        )
    finally:
        axi.kill_agent(name, timeout=60.0)
