# spec: specs/clear-command-confirms.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .helpers import Discord


def test_clear_command_confirms_cleared(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    msg_id = discord.send(master_channel, "/clear")
    deadline = time.monotonic() + 15
    text = ""
    while time.monotonic() < deadline:
        msgs = discord.history(master_channel, limit=5, after=msg_id)
        text = "\n".join(m.get("content", "") for m in msgs).lower()
        if "clear" in text:
            break
        time.sleep(1)
    assert "clear" in text, (
        f"Bot did not confirm /clear within 15s. Got: {text[:300]!r}"
    )
    # allow any awaiting-input sentinel to clear before next test
    time.sleep(3)
