# spec: specs/killed-agent-rejects-messages.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

from .axi_e2e import AxiDiscordEntrypoints
from .conftest import agent_cwd

if TYPE_CHECKING:
    from .helpers import Discord


def test_killed_agent_channel_rejects_messages(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    name = f"smoke-killed-{int(time.time() * 1000)}"
    master = discord.channel(master_channel, name="axi-master")
    axi = AxiDiscordEntrypoints(master)
    killed = False
    try:
        axi.spawn_agent(
            name=name,
            cwd=agent_cwd(name),
            prompt="Say exactly: ALIVE_BEFORE_KILL",
            command="prompt",
            timeout=180.0,
        )
        agent = discord.wait_for_channel(name, timeout=60.0)
        agent.wait_for_bot_response(
            after="0", timeout=120.0, sentinel=None, check="ALIVE_BEFORE_KILL"
        )

        axi.kill_agent(name, timeout=60.0)
        killed = True
        # give Axi a moment to update the channel's state
        time.sleep(2)

        msgs = discord.send_and_wait(
            agent.channel_id,
            "Are you alive?",
            timeout=30.0,
            sentinel=False,
        )
        text = discord.bot_response_text(msgs).lower()
        assert "killed" in text or "has been killed" in text, (
            f"Expected a killed-agent notice, got: {text[:300]!r}"
        )
    finally:
        if not killed:
            axi.kill_agent(name, timeout=60.0)
