# spec: specs/emoji-checkmark-reaction.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .helpers import Discord


CHECKMARK_NAMES = ("\u2705", "\u2611\ufe0f", "\u2611", "\u2713", "white_check_mark")


def test_bot_adds_checkmark_reaction_to_processed_message(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    sentinel = f"REACTION_CHECK_{int(time.time() * 1000)}"
    msg_id = discord.send(master_channel, f"Say exactly: {sentinel}")
    discord.wait_for_bot(master_channel, after=msg_id, timeout=60.0)

    deadline = time.monotonic() + 30.0
    reactions: list = []
    has_check = False
    while time.monotonic() < deadline:
        # discord._bot.get returns the parsed JSON dict already.
        message = discord._bot.get(f"/channels/{master_channel}/messages/{msg_id}")
        reactions = message.get("reactions", []) or []
        has_check = any(
            r.get("emoji", {}).get("name") in CHECKMARK_NAMES for r in reactions
        )
        if has_check:
            break
        time.sleep(1)

    assert has_check, f"No checkmark reaction found after 30s. Reactions: {reactions!r}"
