# spec: specs/basic-echo-master.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .helpers import Discord


def test_master_echoes_sentinel(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    sentinel = f"ECHO_OK_{int(time.time() * 1000)}"
    msgs = discord.send_and_wait(
        master_channel, f"Say exactly: {sentinel}", timeout=120.0
    )
    text = discord.bot_response_text(msgs)
    assert sentinel in text, f"Sentinel {sentinel!r} not found in: {text[:300]!r}"
