# spec: specs/agent-spawn-and-smoke.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

from .axi_e2e import AxiDiscordEntrypoints
from .conftest import agent_cwd

if TYPE_CHECKING:
    from .helpers import Discord


def test_master_spawns_flowcoder_that_echoes_sentinel(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    name = f"smoke-spawn-{int(time.time() * 1000)}"
    master = discord.channel(master_channel, name="axi-master")
    axi = AxiDiscordEntrypoints(master)
    try:
        axi.spawn_agent(
            name=name,
            cwd=agent_cwd(name),
            prompt="Say exactly: SPAWN_SMOKE_OK",
            command="prompt",
            timeout=180.0,
        )
        agent_channel = discord.wait_for_channel(name, timeout=60.0)
        text = agent_channel.wait_for_bot_response(
            after="0",
            timeout=120.0,
            sentinel=None,
            check="SPAWN_SMOKE_OK",
        ).text
        assert "SPAWN_SMOKE_OK" in text, (
            f"Agent output missing sentinel. Got: {text[:300]!r}"
        )
    finally:
        axi.kill_agent(name, timeout=60.0)
