# spec: specs/spawn-and-kill-smoke.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

from .axi_e2e import AxiDiscordEntrypoints
from .conftest import agent_cwd

if TYPE_CHECKING:
    from .helpers import Discord


KILL_CONFIRMATION_PHRASES = ("stopped", "killed", "terminated")


def test_spawn_and_kill_throwaway_flowcoder(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    name = f"smoke-probe-{int(time.time() * 1000)}"
    master = discord.channel(master_channel, name="axi-master")
    axi = AxiDiscordEntrypoints(master)
    try:
        axi.spawn_agent(
            name=name,
            cwd=agent_cwd(name),
            prompt=f"Say exactly: ALIVE_{name}",
            command="prompt",
            timeout=180.0,
        )
        agent = discord.wait_for_channel(name, timeout=60.0)
        agent_text = agent.wait_for_bot_response(
            after="0", timeout=120.0, sentinel=None, check=f"ALIVE_{name}"
        ).text
        assert agent_text.strip(), "Spawned agent produced no output"

        kill_reply = master.send_and_wait(
            f'Kill the agent named "{name}"', timeout=30.0
        )
        # DiscordChannel.send_and_wait goes through Discord.send_and_wait which
        # returns list[dict], not WaitResult. Use bot_response_text to extract.
        kill_text = discord.bot_response_text(kill_reply).lower()
        assert any(phrase in kill_text for phrase in KILL_CONFIRMATION_PHRASES) or (
            name in kill_text
        ), f"Kill not confirmed. Reply was: {kill_text[:300]!r}"
    finally:
        # Best-effort teardown if the kill above did not land.
        try:
            axi.kill_agent(name, timeout=60.0)
        except Exception:
            pass
