# spec: specs/agent-restart-reuses-channel.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

from .axi_e2e import AxiDiscordEntrypoints
from .conftest import agent_cwd

if TYPE_CHECKING:
    from .helpers import Discord


def test_restart_preserves_channel_and_agent_responds(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    name = f"smoke-restart-{int(time.time() * 1000)}"
    master = discord.channel(master_channel, name="axi-master")
    axi = AxiDiscordEntrypoints(master)
    try:
        axi.spawn_agent(
            name=name,
            cwd=agent_cwd(name),
            prompt="Say exactly: FIRST_BOOT",
            command="prompt",
            timeout=180.0,
        )
        agent = discord.wait_for_channel(name, timeout=60.0)
        agent.wait_for_bot_response(
            after="0", timeout=120.0, sentinel=None, check="FIRST_BOOT"
        )
        original_channel_id = agent.channel_id

        axi.restart_agent(name, timeout=90.0)

        reply = agent.send_and_wait(
            "Say exactly: POST_RESTART_OK",
            timeout=120.0,
        )
        reply_text = discord.bot_response_text(reply)
        assert "POST_RESTART_OK" in reply_text, (
            f"Agent did not respond after restart. Got: {reply_text[:300]!r}"
        )
        refreshed = discord.wait_for_channel(name, timeout=10.0)
        assert refreshed.channel_id == original_channel_id, (
            f"Restart created a new channel: before={original_channel_id}, after={refreshed.channel_id}"
        )
    finally:
        axi.kill_agent(name, timeout=60.0)
