# spec: specs/compact-command-reports-tokens.md
"""Generated by the discord-test-generator flowchart. Do not edit by hand."""

from __future__ import annotations

import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .helpers import Discord


def test_compact_command_reports_result(
    discord: Discord, master_channel: str, warmup: None
) -> None:
    msg_id = discord.send(master_channel, "/compact")
    deadline = time.monotonic() + 60
    text = ""
    while time.monotonic() < deadline:
        msgs = discord.history(master_channel, limit=10, after=msg_id)
        text = "\n".join(m.get("content", "") for m in msgs).lower()
        if "compact" in text or "token" in text:
            break
        time.sleep(2)
    assert "compact" in text or "token" in text, (
        f"/compact did not report within 60s. Got: {text[:300]!r}"
    )
    # allow any awaiting-input sentinel to clear before next test
    time.sleep(3)
